apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: boot-configuration
  name: boot-configuration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: boot-configuration
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: boot-configuration
    spec:
      containers:
      - image: josdem/boot-configuration
        name: boot-configuration
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: boot-configuration
  name: boot-configuration
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: boot-configuration
  type: ClusterIP
status:
  loadBalancer: {}
